# Generated by Django 5.2.13 on 2026-04-17 16:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
        ('formsapp', '0002_alter_dynamicform_options_dynamicform_created_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employee',
            options={'ordering': ['-id']},
        ),
        migrations.AddField(
            model_name='employee',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='form',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='formsapp.dynamicform'),
        ),
        migrations.AlterUniqueTogether(
            name='employeefieldvalue',
            unique_together={('employee', 'label')},
        ),
    ]
